### ISSUE TITLE
Invitación para integración de Dataset a nivel latinoamérica

### ISSUE THREAD

**Issue by pablodz** [guberney/Covid_Colombia#1]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En este caso sería Colombia.

El formato de los archivos es el de número de contagiados/muertos/recuperados por departamento por día:

![image](https://user-images.githubusercontent.com/28235457/77831081-ee473380-70fa-11ea-9feb-43fcc0a4f703.png)

Dentro de cada archivo (.csv) respectivo al caso total hasta ese día se tiene que rellenar las siguientes filas:
Por ejemplo para el día [2020-03-28](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-28.csv)

![image](https://user-images.githubusercontent.com/28235457/77855690-ab976100-71b7-11ea-9311-9b2df509ec05.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
Se te puede dar acceso nivel `Maintainer` al repositorio mencionado, ya hay encargados de varios países. Caso contrario puedes comentarnos de alguna persona que sí podría apoyarnos.

**Comment by yammadev** [comment]
@ZurMaD Desde que empezó la pandemia, he estado recopilando los datasets en éste proyecto [yammadev/col-covid-19](https://github.com/yammadev/col-covid-19) para hacer seguimiento (Mapa y Estadísticas) del COVID-19 en Colombia.

Los datos utilizados son cargados (una vez se realiza una actualización) desde los desde los [Datos Abiertos](https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr) del Gobierno Nacional, publicados por el [Ministerio de salud y protección social](https://www.minsalud.gov.co/Paginas/default.aspx) de Colombia y se encuentran formateados disponibles para su estudio y uso en formatos `.csv` y `.json`.

Si sirve de algo, hágame saber. Saludos,

**Comment by pablodz** [comment]
Perfecto, automatizaremos la toma de datos de tu repositorio y lo citaremos. Excelente trabajo.
