### ISSUE TITLE
Del metodo para actualizar los archivos de reportes diarios

### ISSUE THREAD

**Issue by luismanriqueruiz** [guberney/Covid_Colombia#10]
Hola @guberney, gracias por este esfuerzo que continua realizando con este repositorio. La verdad me preguntaba como es el metodo para actualizar estos archivos. Son descargados manualmente y luego enviados al repositorio (manualmente)? Son descargados a la misma hora?. Bueno, me gustaria saber un poco mas de esto, pues pienso que se podria ser automatizado (si no lo fuera).

Un saludo,

**Comment by guberney** [comment]
Hola Luis, te cuento que el método para actualizarlos es manual. Todos los días descargo los datos de datos.gov.co . Lo comencé a hacer manual porque durante un mes los datos fueron controlados por la página de INS, desde el 18 de Abril pasó a la plataforma de datos.gov.co, pero seguí con el mismo método manual. Si puedes ayudar con la automatización, bienvenida. 

Saludos cordiales.

**Comment by luismanriqueruiz** [comment]
@guberney, pensando en ese tema hace un par de días escribí unas funciones en python que me permiten descargar estos archivos cada cierta hora. Estoy preparando un experimento usando un raspberry pie para ejecutarlas y enviar el archivo directo al repositorio (así sea a una rama 'branch'). Pienso en el raspberry pie para no tener que invertirle a una lambda en AWS. A no ser que Guberney conozca un método en la nube sin tener que hacer una inversión de $$.

**Comment by luismanriqueruiz** [comment]
Asi como lo mencione anteriormente ando haciendo pruebas con un Raspberry pi y pareciera ser que funciona bien. De todas maneras note que en ocasiones este queda congelado. No se si es por el sistema operativo o algo diferente. Sigo haciendo la investigacion...

![874c652f-344e-409b-a7a4-9de3f888a6bc](https://user-images.githubusercontent.com/18214791/82753536-59fb0380-9e01-11ea-8885-7ea5d93f03f1.jpg)

P.D.: Perdon por la falta de tildes.
