### ISSUE TITLE
consistencia en nombres de archivos

### ISSUE THREAD

**Issue by luismanriqueruiz** [guberney/Covid_Colombia#8]
Guberney, gracias por este esfuerzo que esta realizando. He notado que los nombres de los archivos  de abril y marzo se encuentran escritos en idioma "espanhol" sin embargo los de mayo estan en "ingles". Podria por favor dejarlos en un mismo idioma, esto con el fin de mantener la consistencia.

**Comment by guberney** [comment]
Hola Luis, tienes razón. Lo voy a cambiar. Saludos.
