### ISSUE TITLE
Datos 08 de mayo

### ISSUE THREAD

**Issue by luismanriqueruiz** [guberney/Covid_Colombia#9]
@guberney, descargue el archivo que otra persona coloco en este repositorio (xlsx) en una estructura diferente. Alli removi una columna, cambie los nombres de las filas para dejarlas en un mismo formato y reorganice su estructura. Esto con el fin de incluirlo en el repositorio.

Perdon la falta de tildes...

[CasosColombia_08Mayo.zip](https://github.com/guberney/Covid_Colombia/files/4628041/CasosColombia_08Mayo.zip)

**Comment by luismanriqueruiz** [comment]
Ah, se me olvido tambien que de una vez inclui el nombre del archivo en el mismo formato.

**Comment by guberney** [comment]
Hola Luis, excelente. Muchas gracias.
